### ISSUE TITLE
ISSN to misc bits map integration

### ISSUE THREAD

**Issue by shadeMe** [ubtue/ub_tools#2032]
- Generate the map file individually for IxTheo and KrimDok at the end of the pipeline.
- Merge the contents safely into the target file on Sobek for use with zts_harvester.

**Comment by ruschein** [comment]
It seems to me that we can't do this as part of the pipelines because we don't have a convenient method of getting the generated files off those systems.

**Comment by ruschein** [comment]
@mtrojan-ub Ich habe heute (8.8.2018) eine neue Version von /usr/local/var/lib/tuelib/issn_to_misc_bits.map auf Sobek installiert.

**Comment by mtrojan-ub** [comment]
Läuft momentan (erfolgreich) über cronjobs auf sobek+ptah.
